---
- name: Create persistent directories for Filebeat
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ owner_uid }}"
    group: "{{ group_uid }}"
    mode: '0755'
  loop:
    - "{{ filebeat_data }}/logs"
    - "{{ filebeat_config }}/certs"
    - "{{ filebeat_config }}/config"


