---
- name: Import createdirs
  ansible.builtin.include_tasks:
    file: "createdirs.yml"
    apply:
      tags: create_dirs
  tags: create_dirs

- name: Import generatetemplates
  ansible.builtin.include_tasks: "generatetemplates.yml"

- name: Import synccerts
  ansible.builtin.include_tasks: "synccerts.yml"

- name: Import filebeat_podman
  ansible.builtin.include_tasks: "filebeat_podman.yml"
